# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 13:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Enter 4 digit year.', regex='^\\d{4}$')])),
                ('details', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Additional Info')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_audio_required', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Book Tag',
            },
        ),
        migrations.CreateModel(
            name='CorrectedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, verbose_name='Corrected Text')),
                ('check_out_time', models.DateTimeField()),
                ('check_in_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrected Result',
            },
        ),
        migrations.CreateModel(
            name='ErrorWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('corrected', models.CharField(max_length=255)),
                ('suggestion_number', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Error Word',
            },
        ),
        migrations.CreateModel(
            name='ErrorWordSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=255)),
                ('suggestion_number', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('error_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ErrorWord')),
            ],
            options={
                'verbose_name': 'Error Word Suggestion',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(default='English', max_length=20)),
                ('postprocessing_enabled', models.BooleanField(default=False)),
                ('dict_file', models.CharField(blank=True, max_length=255)),
                ('vocab_file', models.CharField(blank=True, max_length=255)),
                ('editors', models.ManyToManyField(related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, verbose_name='Recognized Text')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('corrected', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('check_out_time', models.DateTimeField(null=True)),
                ('check_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OCR Result',
            },
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manually_fixed', models.BooleanField(default=False)),
                ('fixed_image', models.ImageField(null=True, upload_to=upload.models.get_segmentation_fixed_image_path)),
                ('segmentation_plot_file', models.FileField(null=True, upload_to=upload.models.get_segmentation_plot_file_path)),
                ('segmentation_plot_image', models.ImageField(null=True, upload_to=upload.models.get_segmentation_plot_image_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to=upload.models.get_zip_upload_path, validators=[upload.models.validate_file_field])),
                ('image', models.FileField(upload_to=upload.models.get_image_upload_path)),
                ('page_number', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('', ''), ('new', 'New'), ('segmented', 'Segmented'), ('queued', 'Queued for manual fix'), ('fixed', 'Manually fixed'), ('processed', 'Processed (OCR + PP)'), ('corrected', 'Corrected'), ('unusable', 'Unusable')], default='new', max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Book')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Language')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
        migrations.AddField(
            model_name='errorword',
            name='ocr_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.OCRResult'),
        ),
        migrations.AddField(
            model_name='correctedresult',
            name='ocr_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.OCRResult'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='upload.BookTag'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Book'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='corrected_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.CorrectedResult'),
        ),
    ]
