# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='book',
            name='zip_file',
            field=models.FileField(blank=True, upload_to=upload.models.get_zip_upload_path),
        ),
    ]
