# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_xmldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='daisy_xml',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='zip_file',
            field=models.FileField(blank=True, upload_to=upload.models.get_zip_upload_path, validators=[upload.models.validate_file_field]),
        ),
    ]
